server:
  port: 8086
spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
    consumer.properties.spring.json.trusted.packages: "*"
